spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
    name: springconfig-test-client2

eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7301/eureka
      
info:
  app.name: springcloud-config-client-devdev
  company.name: enjoy1

---
server:
  port: 8102

spring:
  profiles: beta
  application:
    name: springconfig-test-client2

eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7001/eureka
      
info:
  app.name: springcloud-config-client-devdev
  company.name: enjoy1

